<?php
//Delete all settings first
$wpdb->query("DELETE FROM `".$wpdb->prefix."options` WHERE option_name LIKE '%pp_%'");
$wpdb->query("DELETE FROM `".$wpdb->prefix."options` WHERE option_name LIKE '%ps_%'");

$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8692, 'pp_layerslider_activated', '1', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8693, 'pp_theme_layout', 'fullwidth', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8696, 'pp_body_font_size', '13', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8697, 'pp_menu_font_size', '14', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8698, 'pp_submenu_font_size', '13', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8699, 'pp_menu_uppercase', 'true', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8700, 'pp_font', 'Oswald', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8701, 'pp_page_header_font_size', '24', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8702, 'pp_footer_header_font_size', '13', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8703, 'pp_sidebar_header_font_size', '15', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8704, 'pp_h1_size', '28', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8705, 'pp_h2_size', '24', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8706, 'pp_h3_size', '22', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8707, 'pp_h4_size', '20', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8708, 'pp_h5_size', '16', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8709, 'pp_h6_size', '14', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8710, 'pp_button_bg_color', '#9aca42', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8711, 'pp_button_font_color', '#ffffff', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8712, 'pp_button_border_color', '#9aca42', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8713, 'pp_font_color', '#777777', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8714, 'pp_link_color', '#333333', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8715, 'pp_hover_link_color', '#9aca42', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8716, 'pp_active_link_color', '#333333', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8717, 'pp_h1_font_color', '#111111', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8718, 'pp_page_header_font_color', '#111111', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8719, 'pp_menu_link_color', '#444444', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8720, 'pp_menu_link_hover_color', '#9aca42', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8721, 'pp_submenu_link_color', '#777777', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8722, 'pp_submenu_hover_color', '#9aca42', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8723, 'pp_blog_title_font_color', '#333333', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8724, 'pp_dropcap_bg_color', '#2c2f32', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8725, 'pp_pricing_active_bg_color', '#2c2f32', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8726, 'pp_pricing_default_bg_color', '#F9F9F9', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8727, 'pp_pricing_border_color', '#EBEBEB', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8728, 'pp_footer_widget_title_color', '#ffffff', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8729, 'pp_footer_font_color', '#999999', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8730, 'pp_footer_link_color', '#ffffff', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8731, 'pp_below_footer_color', '#999999', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8732, 'pp_below_footer_background_color', '#1f2224', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8733, 'pp_homepage_header_text', 'We Present Kakia Responsive Business Wordpress Theme', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8734, 'pp_homepage_description_text', 'You can discover many awesome features and the ease of using this theme advanced theme options ', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8736, 'pp_slider_display', 'true', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8737, 'pp_slider_type', 'layerslider', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8738, 'pp_slider_layerslider_id', '9', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8739, 'pp_homepage_transition', '3D', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8740, 'pp_slider_items', '4', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8741, 'pp_slider_timer', '10', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8742, 'pp_portfolio_items', '16', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8743, 'pp_portfolio_enable_feat', 'true', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8744, 'pp_portfolio_enable_recent', 'true', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8745, 'pp_portfolio_recent_items', '12', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8746, 'pp_blog_single_img', 'true', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8748, 'pp_contact_phone', '1800-299-234-22', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8749, 'pp_contact_email', 'contact@kakiacorp.com', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8750, 'pp_contact_address', '77a First Street, London, BC1A 4RT, United Kingdom', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8751, 'pp_contact_email_display', 'true', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8752, 'pp_contact_form', 's:8:\"s:1:\"1\";\";', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8753, 'pp_contact_button_display', 'true', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8754, 'pp_contact_url', '#', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8755, 'pp_contact_display_map', 'true', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8756, 'pp_contact_lat', '40.724755', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8757, 'pp_contact_long', '-74.0107', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8758, 'pp_contact_map_zoom', '16', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8759, 'pp_footer_display_sidebar', 'true', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8760, 'pp_footer_style', '4', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8761, 'pp_footer_text', 'Copyright  2013 Kakia Theme. Powered by Wordpress theme by Peerapong', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8762, 'pp_facebook_username', '#', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8763, 'pp_twitter_username', '#', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8764, 'pp_google_username', '#', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8765, 'pp_flickr_username', '', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8766, 'pp_youtube_username', '', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8767, 'pp_vimeo_username', '', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8768, 'pp_tumblr_username', '', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8769, 'pp_digg_username', '', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8770, 'pp_dribbble_username', '', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8771, 'pp_linkedin_username', '#', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8775, 'pp_advance_enable_custom', 'true', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8776, 'pp_advance_responsive', 'true', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8779, 'pp_font_family', 'Oswald', 'yes');");
$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8781, 'pp_contact_form_sort_data', 's:54:\"a:4:{i:0;s:1:\"1\";i:1;s:1:\"2\";i:2;s:1:\"7\";i:3;s:1:\"3\";}\";', 'yes');");

$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8597, 'ps_1358004403', 'a:3:{s:2:\"id\";s:13:\"ps_1358004403\";s:4:\"name\";s:5:\"Green\";s:8:\"settings\";a:23:{s:13:\"pp_font_color\";s:7:\"#777777\";s:13:\"pp_link_color\";s:7:\"#333333\";s:19:\"pp_hover_link_color\";s:7:\"#9aca42\";s:20:\"pp_active_link_color\";s:7:\"#333333\";s:16:\"pp_h1_font_color\";s:7:\"#111111\";s:25:\"pp_page_header_font_color\";s:7:\"#111111\";s:18:\"pp_menu_link_color\";s:7:\"#444444\";s:24:\"pp_menu_link_hover_color\";s:7:\"#9aca42\";s:21:\"pp_submenu_link_color\";s:7:\"#777777\";s:22:\"pp_submenu_hover_color\";s:7:\"#9aca42\";s:24:\"pp_blog_title_font_color\";s:7:\"#333333\";s:19:\"pp_dropcap_bg_color\";s:7:\"#2c2f32\";s:26:\"pp_pricing_active_bg_color\";s:7:\"#2c2f32\";s:27:\"pp_pricing_default_bg_color\";s:7:\"#F9F9F9\";s:23:\"pp_pricing_border_color\";s:7:\"#EBEBEB\";s:28:\"pp_footer_widget_title_color\";s:7:\"#ffffff\";s:20:\"pp_footer_font_color\";s:7:\"#999999\";s:20:\"pp_footer_link_color\";s:7:\"#ffffff\";s:21:\"pp_below_footer_color\";s:7:\"#999999\";s:32:\"pp_below_footer_background_color\";s:7:\"#1f2224\";s:18:\"pp_button_bg_color\";s:7:\"#9aca42\";s:20:\"pp_button_font_color\";s:7:\"#ffffff\";s:22:\"pp_button_border_color\";s:7:\"#9aca42\";}}', 'yes');");

$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8598, 'ps_1358005617', 'a:3:{s:2:\"id\";s:13:\"ps_1358005617\";s:4:\"name\";s:4:\"Blue\";s:8:\"settings\";a:23:{s:13:\"pp_font_color\";s:7:\"#777777\";s:13:\"pp_link_color\";s:7:\"#333333\";s:19:\"pp_hover_link_color\";s:7:\"#4fcaf0\";s:20:\"pp_active_link_color\";s:7:\"#333333\";s:16:\"pp_h1_font_color\";s:7:\"#111111\";s:25:\"pp_page_header_font_color\";s:7:\"#000000\";s:18:\"pp_menu_link_color\";s:7:\"#333333\";s:24:\"pp_menu_link_hover_color\";s:7:\"#4fcaf0\";s:21:\"pp_submenu_link_color\";s:7:\"#777777\";s:22:\"pp_submenu_hover_color\";s:7:\"#4fcaf0\";s:24:\"pp_blog_title_font_color\";s:7:\"#111111\";s:19:\"pp_dropcap_bg_color\";s:7:\"#2c2f32\";s:26:\"pp_pricing_active_bg_color\";s:7:\"#2c2f32\";s:27:\"pp_pricing_default_bg_color\";s:7:\"#F9F9F9\";s:23:\"pp_pricing_border_color\";s:7:\"#EBEBEB\";s:28:\"pp_footer_widget_title_color\";s:7:\"#ffffff\";s:20:\"pp_footer_font_color\";s:7:\"#999999\";s:20:\"pp_footer_link_color\";s:7:\"#ffffff\";s:21:\"pp_below_footer_color\";s:7:\"#999999\";s:32:\"pp_below_footer_background_color\";s:7:\"#1f2224\";s:18:\"pp_button_bg_color\";s:7:\"#4fcaf0\";s:20:\"pp_button_font_color\";s:7:\"#ffffff\";s:22:\"pp_button_border_color\";s:7:\"#4fcaf0\";}}', 'yes');");

$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8599, 'ps_1358005683', 'a:3:{s:2:\"id\";s:13:\"ps_1358005683\";s:4:\"name\";s:6:\"Orange\";s:8:\"settings\";a:23:{s:13:\"pp_font_color\";s:7:\"#777777\";s:13:\"pp_link_color\";s:7:\"#333333\";s:19:\"pp_hover_link_color\";s:7:\"#f17007\";s:20:\"pp_active_link_color\";s:7:\"#333333\";s:16:\"pp_h1_font_color\";s:7:\"#111111\";s:25:\"pp_page_header_font_color\";s:7:\"#000000\";s:18:\"pp_menu_link_color\";s:7:\"#333333\";s:24:\"pp_menu_link_hover_color\";s:7:\"#f17007\";s:21:\"pp_submenu_link_color\";s:7:\"#777777\";s:22:\"pp_submenu_hover_color\";s:7:\"#f17007\";s:24:\"pp_blog_title_font_color\";s:7:\"#111111\";s:19:\"pp_dropcap_bg_color\";s:7:\"#2c2f32\";s:26:\"pp_pricing_active_bg_color\";s:7:\"#2c2f32\";s:27:\"pp_pricing_default_bg_color\";s:7:\"#F9F9F9\";s:23:\"pp_pricing_border_color\";s:7:\"#EBEBEB\";s:28:\"pp_footer_widget_title_color\";s:7:\"#ffffff\";s:20:\"pp_footer_font_color\";s:7:\"#999999\";s:20:\"pp_footer_link_color\";s:7:\"#ffffff\";s:21:\"pp_below_footer_color\";s:7:\"#999999\";s:32:\"pp_below_footer_background_color\";s:7:\"#1f2224\";s:18:\"pp_button_bg_color\";s:7:\"#f17007\";s:20:\"pp_button_font_color\";s:7:\"#ffffff\";s:22:\"pp_button_border_color\";s:7:\"#f17007\";}}', 'yes');");

$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8600, 'ps_1358005723', 'a:3:{s:2:\"id\";s:13:\"ps_1358005723\";s:4:\"name\";s:4:\"Grey\";s:8:\"settings\";a:23:{s:13:\"pp_font_color\";s:7:\"#777777\";s:13:\"pp_link_color\";s:7:\"#333333\";s:19:\"pp_hover_link_color\";s:7:\"#929aa1\";s:20:\"pp_active_link_color\";s:7:\"#333333\";s:16:\"pp_h1_font_color\";s:7:\"#111111\";s:25:\"pp_page_header_font_color\";s:7:\"#000000\";s:18:\"pp_menu_link_color\";s:7:\"#333333\";s:24:\"pp_menu_link_hover_color\";s:7:\"#929aa1\";s:21:\"pp_submenu_link_color\";s:7:\"#777777\";s:22:\"pp_submenu_hover_color\";s:7:\"#929aa1\";s:24:\"pp_blog_title_font_color\";s:7:\"#111111\";s:19:\"pp_dropcap_bg_color\";s:7:\"#2c2f32\";s:26:\"pp_pricing_active_bg_color\";s:7:\"#2c2f32\";s:27:\"pp_pricing_default_bg_color\";s:7:\"#F9F9F9\";s:23:\"pp_pricing_border_color\";s:7:\"#EBEBEB\";s:28:\"pp_footer_widget_title_color\";s:7:\"#ffffff\";s:20:\"pp_footer_font_color\";s:7:\"#999999\";s:20:\"pp_footer_link_color\";s:7:\"#ffffff\";s:21:\"pp_below_footer_color\";s:7:\"#999999\";s:32:\"pp_below_footer_background_color\";s:7:\"#1f2224\";s:18:\"pp_button_bg_color\";s:7:\"#929aa1\";s:20:\"pp_button_font_color\";s:7:\"#ffffff\";s:22:\"pp_button_border_color\";s:7:\"#929aa1\";}}', 'yes');");

$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8601, 'ps_1358005776', 'a:3:{s:2:\"id\";s:13:\"ps_1358005776\";s:4:\"name\";s:3:\"Red\";s:8:\"settings\";a:23:{s:13:\"pp_font_color\";s:7:\"#777777\";s:13:\"pp_link_color\";s:7:\"#333333\";s:19:\"pp_hover_link_color\";s:7:\"#d41e1e\";s:20:\"pp_active_link_color\";s:7:\"#333333\";s:16:\"pp_h1_font_color\";s:7:\"#111111\";s:25:\"pp_page_header_font_color\";s:7:\"#000000\";s:18:\"pp_menu_link_color\";s:7:\"#333333\";s:24:\"pp_menu_link_hover_color\";s:7:\"#d41e1e\";s:21:\"pp_submenu_link_color\";s:7:\"#777777\";s:22:\"pp_submenu_hover_color\";s:7:\"#d41e1e\";s:24:\"pp_blog_title_font_color\";s:7:\"#111111\";s:19:\"pp_dropcap_bg_color\";s:7:\"#2c2f32\";s:26:\"pp_pricing_active_bg_color\";s:7:\"#2c2f32\";s:27:\"pp_pricing_default_bg_color\";s:7:\"#F9F9F9\";s:23:\"pp_pricing_border_color\";s:7:\"#EBEBEB\";s:28:\"pp_footer_widget_title_color\";s:7:\"#ffffff\";s:20:\"pp_footer_font_color\";s:7:\"#999999\";s:20:\"pp_footer_link_color\";s:7:\"#ffffff\";s:21:\"pp_below_footer_color\";s:7:\"#999999\";s:32:\"pp_below_footer_background_color\";s:7:\"#1f2224\";s:18:\"pp_button_bg_color\";s:7:\"#d41e1e\";s:20:\"pp_button_font_color\";s:7:\"#ffffff\";s:22:\"pp_button_border_color\";s:7:\"#d41e1e\";}}', 'yes');");

$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8602, 'ps_1358005809', 'a:3:{s:2:\"id\";s:13:\"ps_1358005809\";s:4:\"name\";s:4:\"Pink\";s:8:\"settings\";a:23:{s:13:\"pp_font_color\";s:7:\"#777777\";s:13:\"pp_link_color\";s:7:\"#333333\";s:19:\"pp_hover_link_color\";s:7:\"#ed6280\";s:20:\"pp_active_link_color\";s:7:\"#333333\";s:16:\"pp_h1_font_color\";s:7:\"#111111\";s:25:\"pp_page_header_font_color\";s:7:\"#000000\";s:18:\"pp_menu_link_color\";s:7:\"#333333\";s:24:\"pp_menu_link_hover_color\";s:7:\"#ed6280\";s:21:\"pp_submenu_link_color\";s:7:\"#777777\";s:22:\"pp_submenu_hover_color\";s:7:\"#ed6280\";s:24:\"pp_blog_title_font_color\";s:7:\"#111111\";s:19:\"pp_dropcap_bg_color\";s:7:\"#2c2f32\";s:26:\"pp_pricing_active_bg_color\";s:7:\"#2c2f32\";s:27:\"pp_pricing_default_bg_color\";s:7:\"#F9F9F9\";s:23:\"pp_pricing_border_color\";s:7:\"#EBEBEB\";s:28:\"pp_footer_widget_title_color\";s:7:\"#ffffff\";s:20:\"pp_footer_font_color\";s:7:\"#999999\";s:20:\"pp_footer_link_color\";s:7:\"#ffffff\";s:21:\"pp_below_footer_color\";s:7:\"#999999\";s:32:\"pp_below_footer_background_color\";s:7:\"#1f2224\";s:18:\"pp_button_bg_color\";s:7:\"#ed6280\";s:20:\"pp_button_font_color\";s:7:\"#ffffff\";s:22:\"pp_button_border_color\";s:7:\"#ed6280\";}}', 'yes');");

$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8603, 'ps_1358005844', 'a:3:{s:2:\"id\";s:13:\"ps_1358005844\";s:4:\"name\";s:5:\"Ocean\";s:8:\"settings\";a:23:{s:13:\"pp_font_color\";s:7:\"#777777\";s:13:\"pp_link_color\";s:7:\"#333333\";s:19:\"pp_hover_link_color\";s:7:\"#5ad1c1\";s:20:\"pp_active_link_color\";s:7:\"#333333\";s:16:\"pp_h1_font_color\";s:7:\"#111111\";s:25:\"pp_page_header_font_color\";s:7:\"#000000\";s:18:\"pp_menu_link_color\";s:7:\"#333333\";s:24:\"pp_menu_link_hover_color\";s:7:\"#5ad1c1\";s:21:\"pp_submenu_link_color\";s:7:\"#777777\";s:22:\"pp_submenu_hover_color\";s:7:\"#5ad1c1\";s:24:\"pp_blog_title_font_color\";s:7:\"#111111\";s:19:\"pp_dropcap_bg_color\";s:7:\"#2c2f32\";s:26:\"pp_pricing_active_bg_color\";s:7:\"#2c2f32\";s:27:\"pp_pricing_default_bg_color\";s:7:\"#F9F9F9\";s:23:\"pp_pricing_border_color\";s:7:\"#EBEBEB\";s:28:\"pp_footer_widget_title_color\";s:7:\"#ffffff\";s:20:\"pp_footer_font_color\";s:7:\"#999999\";s:20:\"pp_footer_link_color\";s:7:\"#ffffff\";s:21:\"pp_below_footer_color\";s:7:\"#999999\";s:32:\"pp_below_footer_background_color\";s:7:\"#1f2224\";s:18:\"pp_button_bg_color\";s:7:\"#5ad1c1\";s:20:\"pp_button_font_color\";s:7:\"#ffffff\";s:22:\"pp_button_border_color\";s:7:\"#5ad1c1\";}}', 'yes');");

$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8604, 'ps_1358005876', 'a:3:{s:2:\"id\";s:13:\"ps_1358005876\";s:4:\"name\";s:4:\"Gold\";s:8:\"settings\";a:23:{s:13:\"pp_font_color\";s:7:\"#777777\";s:13:\"pp_link_color\";s:7:\"#333333\";s:19:\"pp_hover_link_color\";s:7:\"#d6b962\";s:20:\"pp_active_link_color\";s:7:\"#333333\";s:16:\"pp_h1_font_color\";s:7:\"#111111\";s:25:\"pp_page_header_font_color\";s:7:\"#000000\";s:18:\"pp_menu_link_color\";s:7:\"#333333\";s:24:\"pp_menu_link_hover_color\";s:7:\"#d6b962\";s:21:\"pp_submenu_link_color\";s:7:\"#777777\";s:22:\"pp_submenu_hover_color\";s:7:\"#d6b962\";s:24:\"pp_blog_title_font_color\";s:7:\"#111111\";s:19:\"pp_dropcap_bg_color\";s:7:\"#2c2f32\";s:26:\"pp_pricing_active_bg_color\";s:7:\"#2c2f32\";s:27:\"pp_pricing_default_bg_color\";s:7:\"#F9F9F9\";s:23:\"pp_pricing_border_color\";s:7:\"#EBEBEB\";s:28:\"pp_footer_widget_title_color\";s:7:\"#ffffff\";s:20:\"pp_footer_font_color\";s:7:\"#999999\";s:20:\"pp_footer_link_color\";s:7:\"#ffffff\";s:21:\"pp_below_footer_color\";s:7:\"#999999\";s:32:\"pp_below_footer_background_color\";s:7:\"#1f2224\";s:18:\"pp_button_bg_color\";s:7:\"#d6b962\";s:20:\"pp_button_font_color\";s:7:\"#ffffff\";s:22:\"pp_button_border_color\";s:7:\"#d6b962\";}}', 'yes');");

$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8605, 'ps_1358005918', 'a:3:{s:2:\"id\";s:13:\"ps_1358005918\";s:4:\"name\";s:6:\"Purple\";s:8:\"settings\";a:23:{s:13:\"pp_font_color\";s:7:\"#777777\";s:13:\"pp_link_color\";s:7:\"#333333\";s:19:\"pp_hover_link_color\";s:7:\"#cbaae0\";s:20:\"pp_active_link_color\";s:7:\"#333333\";s:16:\"pp_h1_font_color\";s:7:\"#111111\";s:25:\"pp_page_header_font_color\";s:7:\"#000000\";s:18:\"pp_menu_link_color\";s:7:\"#333333\";s:24:\"pp_menu_link_hover_color\";s:7:\"#cbaae0\";s:21:\"pp_submenu_link_color\";s:7:\"#777777\";s:22:\"pp_submenu_hover_color\";s:7:\"#cbaae0\";s:24:\"pp_blog_title_font_color\";s:7:\"#111111\";s:19:\"pp_dropcap_bg_color\";s:7:\"#2c2f32\";s:26:\"pp_pricing_active_bg_color\";s:7:\"#2c2f32\";s:27:\"pp_pricing_default_bg_color\";s:7:\"#F9F9F9\";s:23:\"pp_pricing_border_color\";s:7:\"#EBEBEB\";s:28:\"pp_footer_widget_title_color\";s:7:\"#ffffff\";s:20:\"pp_footer_font_color\";s:7:\"#999999\";s:20:\"pp_footer_link_color\";s:7:\"#ffffff\";s:21:\"pp_below_footer_color\";s:7:\"#999999\";s:32:\"pp_below_footer_background_color\";s:7:\"#1f2224\";s:18:\"pp_button_bg_color\";s:7:\"#cbaae0\";s:20:\"pp_button_font_color\";s:7:\"#ffffff\";s:22:\"pp_button_border_color\";s:7:\"#cbaae0\";}}', 'yes');");

$wpdb->query("INSERT IGNORE INTO `".$wpdb->prefix."options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES(8606, 'ps_1358005947', 'a:3:{s:2:\"id\";s:13:\"ps_1358005947\";s:4:\"name\";s:11:\"Purple Blue\";s:8:\"settings\";a:23:{s:13:\"pp_font_color\";s:7:\"#777777\";s:13:\"pp_link_color\";s:7:\"#333333\";s:19:\"pp_hover_link_color\";s:7:\"#7dadff\";s:20:\"pp_active_link_color\";s:7:\"#333333\";s:16:\"pp_h1_font_color\";s:7:\"#111111\";s:25:\"pp_page_header_font_color\";s:7:\"#000000\";s:18:\"pp_menu_link_color\";s:7:\"#333333\";s:24:\"pp_menu_link_hover_color\";s:7:\"#777777\";s:21:\"pp_submenu_link_color\";s:7:\"#cccccc\";s:22:\"pp_submenu_hover_color\";s:7:\"#7dadff\";s:24:\"pp_blog_title_font_color\";s:7:\"#111111\";s:19:\"pp_dropcap_bg_color\";s:7:\"#2c2f32\";s:26:\"pp_pricing_active_bg_color\";s:7:\"#2c2f32\";s:27:\"pp_pricing_default_bg_color\";s:7:\"#F9F9F9\";s:23:\"pp_pricing_border_color\";s:7:\"#EBEBEB\";s:28:\"pp_footer_widget_title_color\";s:7:\"#ffffff\";s:20:\"pp_footer_font_color\";s:7:\"#999999\";s:20:\"pp_footer_link_color\";s:7:\"#ffffff\";s:21:\"pp_below_footer_color\";s:7:\"#999999\";s:32:\"pp_below_footer_background_color\";s:7:\"#1f2224\";s:18:\"pp_button_bg_color\";s:7:\"#7dadff\";s:20:\"pp_button_font_color\";s:7:\"#ffffff\";s:22:\"pp_button_border_color\";s:7:\"#7dadff\";}}', 'yes');");
?>